spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springz
    username: postgres
    password: 4664
  jpa:
    show-sql: false
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: update